# Generated by Django 5.2.1 on 2025-11-18 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
