# Generated by Django 5.2.1 on 2025-11-18 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_booking_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
